---

- name: Update apt cache
  apt:  update_cache=yes
  sudo: yes

- name: Upgrade existing linux packages
  apt:  upgrade=dist
  sudo: yes

- name: Install required packages
  apt:  name={{ item }} update_cache=true state=latest
  sudo: yes
  with_items:
    - autoconf
    - automake
    - bash
    - bison
    - build-essential
    - curl
    - git
    - sqlite3
    - htop
    - iftop
    - libxml2-dev
    - libffi-dev
    - libyaml-dev
    - libssl-dev
    - libsqlite3-dev
    - libgdbm-dev
    - libncurses5-dev
    - libreadline6-dev
    - libtool
    - libyaml-dev
    - libsqlite3-dev
    - pkg-config
    - zlib1g-dev

